#!/bin/bash

. "${SHELL_DIR}/git-completions"

E="\\["

branch() {
  git branch 2>/dev/null | grep '^*' | colrm 1 1
  # | sed 's/$/ /g'
}

function parse_git_dirty {
  [[ "$(git status --porcelain 2> /dev/null | tail -n1)"  != "" ]] && echo "~" || echo " "
}


# dirty() {
#   ([[ $(git status --porcelain 2>/dev/null | tail -n1) != "" ]] && printf "\b\033[0;31m~")
# }


export PS1="\[\033[0;36m\]\\W\[\033[033m\]\$(branch)\[\033[0;31m\]\$(parse_git_dirty)\[\033[0m\]\\$ "

