#!/bin/sh

# Vim Commands
alias :q!=exit
alias :q=exit
export ECLIM_SERVER_SCRIPT="${CFG_DIR}/programs/neovim/eclimd"

# SSH
alias ssh='TERM=xterm-256color ssh'

# tree and ls using exa instead
alias tree='exa -T'
alias ls=exa

# Git
function branch() {
    >&2 echo "Getting current branch..."
    current="$("git" branch | grep \* | cut -d " " -f2)"

    if [ "$current" = "" ]
    then
        return 1
    fi

    >&2 echo "Current branch is ${current}"
    if (( $# != 0 ))
    then
        current="$1"
        >&2 "git" checkout "${current}"
    fi
    echo "${current}"
}

# https://stackoverflow.com/questions/6759791/how-do-i-move-forward-and-backward-between-commits-in-git
function git_gofwd() {
  git checkout $(git rev-list --topo-order HEAD.."$*" | tail -1)
}

# PYTHON

# export PATH="/anaconda3/bin:$PATH"
alias python="python3"
alias pip="pip3"

# Default python development environment to fuck around in
export PYDEVENV=~/.pydenv/bin/activate
function pydev() {
    deactivate 2>/dev/null
    # || deactivate_conda_env
    if [ $# = 0 ]
    then
        echo "Entering default python development environment..."
        source "$PYDEVENV"
    else
        echo "executing \`source ${1}/bin/activate\`"
        source "$1/bin/activate"
    fi
    echo "Created alias 'deactivate' to exit environment."
}

# # ANACONDA
# export CONDA_SETUP=0
# function deactivate_conda_env() {
#     conda deactivate 2>/dev/null &&
#     conda deactivate 2>/dev/null
#     unalias deactivate 2>/dev/null &&
#     echo "Exited from conda environment."
# }
# function condadev() {
#     deactivate 2>/dev/null || deactivate_conda_env
#     if (( "$CONDA_SETUP" == 0 ))
#     then
#         # Setup script to add conda to path
#         source /anaconda3/etc/profile.d/conda.sh
#         export CONDA_SETUP=1
#     fi
#
#     if [ $# = 0 ]
#     then
#         echo "No args => Entering default conda environment..."
#         conda activate conda-default-env
#     else
#         echo "Input was '$1' => executing `conda activate $1`"
#         conda activate $1
#     fi
#     alias deactivate="deactivate_conda_env"
#     echo "Created alias 'deactivate' to exit environment."
# }

# RUBY
alias ruby_setup="export PATH=\"\$HOME/.rbenv/bin:\$PATH\" && eval \"\$(rbenv init -)\" && alias ruby_setup=true"
alias jekyll="ruby_setup && unalias jekyll && jekyll"

# Node
alias gulp="npm run gulp"
alias load_nvm='export PATH="$PATH:$HOME/.nvm" && export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && alias load_nvm=true'
alias node='unalias node && load_nvm && node'
alias npm='unalias npm && load_nvm && npm'
alias prettier='unalias prettier && load_nvm && prettier'

