#!/bin/sh

# Vim Commands
alias :q!=exit
alias :q=exit
alias :ex=vim
alias vi=vim
alias di='VIM_DEBUG=1 vim'

# Eclim
export ECLIM_SERVER_SCRIPT="${CFG_DIR}/programs/neovim/eclimd"

# SSH
alias ssh='TERM=xterm-256color ssh'

# Tmux
alias aliu='tmux attach -t aliu || tmux new -s aliu'

# Disable <C-s> behavior
stty -ixon

alias gs="ls && echo && git s"

# The open command
if command -v 'xdg-open' >/dev/null 2>&1 ; then
  alias open=xdg-open
fi

# tree and ls using exa instead
# alias tree='exa -T'
# alias ls=exa

alias groot='cd "$(git root)"'

# Git
function branch() {
    >&2 echo "Getting current branch..."
    current="$("git" branch | grep \* | cut -d " " -f2)"

    if [ "$current" = "" ]
    then
        return 1
    fi

    >&2 echo "Current branch is ${current}"
    if (( $# != 0 ))
    then
        current="$1"
        >&2 "git" checkout "${current}"
    fi
    echo "${current}"
}

# https://stackoverflow.com/questions/6759791/how-do-i-move-forward-and-backward-between-commits-in-git
function git_gofwd() {
  git checkout $(git rev-list --topo-order HEAD.."$*" | tail -1)
}

# PYTHON

alias python="python3"
alias pip="pip3"

# Default python development environment to fuck around in
export PYDEVENV=~/.pydenv/bin/activate
function pydev() {
    # Deactivate previous environment
    deactivate 2>/dev/null
    # || deactivate_conda_env
    if [ $# = 0 ]
    then
        echo "Entering default python development environment..."
        source "$PYDEVENV"
    else
        echo "executing \`source ${1}/bin/activate\`"
        source "$1/bin/activate"
    fi
    echo "Created alias 'deactivate' to exit environment."
}

# RUBY
alias ruby_setup='export PATH="$HOME/.rbenv/bin:$PATH" && eval "$(rbenv init -)" && alias ruby_setup=true'
alias gem='ruby_setup && unalias gem && gem'
alias bundle='ruby_setup && unalias bundle && bundle'
alias jekyll='ruby_setup && unalias jekyll && jekyll'

function load_nvm() {
  export PATH="$PATH:$HOME/.nvm" && export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  alias load_nvm=true
}

# Node
function nvm() {
  load_nvm
  nvm
}

alias gulp='npm run gulp'
alias node='unalias node && load_nvm && node'
alias npm='unalias npm && load_nvm && npm'
alias prettier='unalias prettier && load_nvm && prettier'
alias npx='unalias npx && load_nvm && npx'
alias firebase='unalias firebase && load_nvm && firebase'

