#!/bin/sh

# Contains common functions, and also handles dispatch to shell-specific setup code.

# See /install/shell for the definitions of the variables 'CFG_DIR', 'CUR_SHELL',
# and 'IS_INTERACTIVE_SHELL'.
export SHELL_DIR="$CFG_DIR/shells"

# Set environment variables that should exist for all calls of a shell
source "$SHELL_DIR/env"

# Get rid of the "login shell" dash prefix because it doesn't help me
shell_path="$(echo "$SHELL_DIR/${CUR_SHELL}"| tr -d "-")"

# If we're interactive, dispatch to shells/bash-interact or something like it,
# instead of shells/bash
if [ $IS_INTERACTIVE_SHELL = true ]; then
  source "$SHELL_DIR/common-interact"
  shell_path="${shell_path}-interact"
fi

# Source shell-specific stuff
if [ -e $shell_path ]; then
  source $shell_path
fi

