#!/bin/sh

# Contains common functions, and also handles dispatch to shell-specific setup code.

export SHELL_DIR="$CFG_DIR/shells"
source "$SHELL_DIR/env"

if [[ $SHELL_TYPE = "login" ]]
then
  source "$SHELL_DIR/login/common"
  shell_path="$SHELL_DIR/login/${CUR_SHELL:1}"
  if [ -e $shell_path ]
  then
    source $shell_path
  fi
fi

