#!/bin/zsh

skip_global_compinit=1

source "$(dirname $0)/zsh/prompt"
source "$(dirname $0)/zsh/key-bindings"
source "$(dirname $0)/git-completions"
zstyle ':completion:*:*:git:*' script "$(dirname $0)/zsh/git-completions"
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Stolen shamelessly from Oh-my-zsh
# https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/history.zsh
#
# History file configuration
[ -z "$HISTFILE" ] && HISTFILE="$CFG_DIR/local/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000


# Stolen shamelessly from Oh-my-zsh
# https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/history.zsh
#
# History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion before running
setopt inc_append_history     # add commands to HISTFILE in order of execution
setopt share_history          # share command history data

