#!/bin/sh

# Contains common functions, and also handles dispatch to shell-specific setup code.

# See /install/shell for the definitions of the variables 'CFG_DIR', 'CUR_SHELL',
# and 'IS_INTERACTIVE_SHELL'.
export SHELL_DIR="$CFG_DIR/shell"


# Set environment variables that should exist for all calls of a shell
. "$SHELL_DIR/env"

shell_path="$SHELL_DIR/${CUR_SHELL}"

# If we're interactive, dispatch to shells/bash-interact or something like it,
# instead of shells/bash
if [ $IS_INTERACTIVE_SHELL = true ]; then
  . "$SHELL_DIR/common-interact"
  shell_path="${shell_path}-interact"

  # Source shell-specific stuff
  if [ -e $shell_path ]; then
    . $shell_path
  fi
fi


