#!/bin/zsh

# set PATH so it includes user's private bin directories
PATH="$HOME/bin:$HOME/.local/bin:$PATH"

export PATH="$HOME/.cargo/bin:$PATH"

conky -c $(dirname $0)/conky_gcalcli_calw
conky -c $(dirname $0)/conky_gcalcli_agenda
setxkbmap -option caps:ctr_modifier
