#!/bin/zsh

local ret_status="%(?:%{$fg[green]%}➜ :%{$fg[red]%}➜ )"
PROMPT='%{$fg[cyan]%}%c%{$reset_color%} \
$(git_prompt_info)${ret_status}%{$reset_color%}'

# https://gist.github.com/vergenzt/33a45a9a9218b38bd4bf
local git_status_prefix="("
local git_status_suffix="%{$fg[yellow]%})"
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[yellow]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="${git_status_prefix}%{$fg[red]%}✗${git_status_suffix}"
ZSH_THEME_GIT_PROMPT_CLEAN=""
# ZSH_THEME_GIT_PROMPT_MODIFIED="mod"

# declare -A EMOJI_LIST
# EMOJI_LIST[rainbow]="🌈"
# EMOJI_LIST[panda]="🐼"
# EMOJI_NUMBERS=(0️⃣  1️⃣  2️⃣  3️⃣  4️⃣  5️⃣  6️⃣  7️⃣  8️⃣  9️⃣ )
# choose_emoji() {
#   printf "%s" "${EMOJI_LIST[panda]}"
# }

# prompt_context() {
#   if [[ -n "$SSH_CLIENT" ]]; then
#     prompt_segment black default "%(!.%{%F{yellow}%}.)$USER"
#   elif [[ "$USER" == "aliu" ]]; then
#     prompt_segment black default $(choose_emoji)
#   else
#     prompt_segment black default "$USER"
#   fi
# }
#
# # Commands for prompt stuff
# alias terse="prompt_dir() {; prompt_segment blue black '%c'; }"
# alias verbose="prompt_dir() {; prompt_segment blue black '%~'; }"
# terse


