#!/bin/zsh

local ret_status="%(?:%{$fg[green]%}➜ :%{$fg[red]%}➜ )"
PROMPT='%{$fg[magenta]%}$(prompt_context)%{$fg[cyan]%}%c%{$reset_color%} \
$(git_prompt_info)${ret_status}%{$reset_color%}'

# https://gist.github.com/vergenzt/33a45a9a9218b38bd4bf
local git_status_prefix="("
local git_status_suffix="%{$fg[yellow]%})"
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[yellow]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="${git_status_prefix}%{$fg[red]%}✗${git_status_suffix}"
ZSH_THEME_GIT_PROMPT_CLEAN=""
# ZSH_THEME_GIT_PROMPT_MODIFIED="mod"

# declare -A EMOJI_LIST
# EMOJI_LIST[rainbow]="🌈"
# EMOJI_LIST[panda]="🐼"

# choose_emoji() {
#   printf "%s" "${EMOJI_LIST[panda]}"
# }

prompt_context() {
  if [[ -n "$SSH_CLIENT" ]]; then
    echo -n "%n@%m "
  elif [[ "$USER" == "aliu" ]]; then
    echo -n ""
  else
    echo -n "%n "
  fi
}

#
# # Commands for prompt stuff
# alias terse="prompt_dir() {; prompt_segment blue black '%c'; }"
# alias verbose="prompt_dir() {; prompt_segment blue black '%~'; }"
# terse


