#!/bin/zsh
export SHELL_DIR="$(dirname "$0")"
export CFG_DIR="$(dirname "$SHELL_DIR")"
export ZSHENV_EXPORT=1

# Adding stuff to python path
export PYTHONPATH="/Users/aliu/code/python/utils:${PYTHONPATH}"

# Setting PATH for Python 3.7
export PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"

export PATH=$PATH:/Users/aliu/.nvm

# RUBY
export PATH="$HOME/.rbenv/bin:$PATH"

# Haskell
source $HOME/.ghcup/env
export PATH="$HOME/.ghcup/env:$PATH"

# Rust
source $HOME/.cargo/env
export PATH="$HOME/.cargo/bin:$PATH"
