#!/bin/zsh

if [[ $ZSHENV_EXPORT != 1 ]]; then
  export SHELL_DIR="$(dirname "$0")"
  export CFG_DIR="$(dirname "$SHELL_DIR")"
  export ZSHENV_EXPORT=1

  # Takes as arguments:
  # 1. path to source
  # 2. command that should be available after source
  source_if_necessary() {
    if [ -e $2 ] && !command -v $1 >/dev/null 2>&1
    then
      source $1
    else
    fi
  }

  # Haskell
  source_if_necessary $HOME/.ghcup/env cabal

  # Rust
  source_if_necessary $HOME/.cargo/env cargo
fi
