#!/bin/bash

# Assumes Git has already been installed
project="$(dirname $0)"
project="$(dirname "$project")"

sudo echo
sudo chsh -s /bin/bash

# Install Homebrew
URL_BREW='https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh'
/bin/bash -c "$(curl -fsSL $URL_BREW)"

export PATH="/opt/homebrew/bin:$PATH"
echo "\n/opt/homebrew/bin\n" | sudo tee -a /etc/paths

brew cleanup

echo "Installing Vim"
brew install vim
echo "Installing git-lfs"
brew install git git-lfs

echo "Installing miscellaneous software..."
brew install fswatch
brew install --cask spotify slack

# Tmux
echo "Installing tmux and related integrations..."
brew install tmux \
&& tic -x "$project/programs/xterm-256color-italic.terminfo" \
&& tic -x "$project/programs/tmux-256color.terminfo"

# Install nvm
echo "Installing Node version manager..."
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash

# Install Python
echo "Installing Python (dependency of shell configs)..."
brew install python@3.9

echo "Installing programming languages..."
echo "  - JavaScript"
nvm install v12.13.0
echo "  - Java"
brew install --cask java
echo "  - Rust"
curl https://sh.rustup.rs -sSf | sh -s -- -y
echo "  - C"
brew install cmake
echo "  - C++"
brew install clang-format
echo "  - Ruby"
brew install rbenv
rbenv install 2.6.3

echo "Installing tooling..."

echo "  - Ripgrep"
brew install ripgrep

echo "  - fd"
brew install fd
