#!/bin/sh

UNDO_DIR="$(dirname "$(realpath "$0")")"
INSTALL_DIR="$(dirname "$UNDO_DIR")"
CFG_DIR="$(dirname "$INSTALL_DIR")"

LOCAL_DIR="${CFG_DIR}/local"
MOVE_DIR="${LOCAL_DIR}/preconf"

if [ "$DEBUG" = "true" ]; then
  echo "Config directory is:         $CFG_DIR"
  echo "Installation directory is:   $INSTALL_DIR"
  echo "Undo directory is:           $UNDO_DIR"
  echo "Machine-local directory is:  $LOCAL_DIR"
  echo "Preconfig directory is:      $MOVE_DIR"
fi

restore_move() {
  DEST="$(echo "~/$1" | tr -s "/")"
  LINK="$(echo "${CFG_DIR}/$1" | tr -s "/")"

  if [ "$DEBUG" = "true" ]; then
    echo "restore_move'ing file path '$LINK' to '$DEST'"
  fi

  # Remove my configs
  rm -f "$DEST"

  # Add back old configs if they existed
  if [ -e "$LINK" ]; then
    mv "$LINK" "$DEST"
  fi
}

restore_move .vimrc
restore_move .vim
restore_move .bashrc
restore_move .bash_profile
restore_move .zshrc
restore_move .gitconfig
restore_move .gitignore_global
restore_move .tmux.conf

