#!/bin/bash

# Assumes Git has already been installed
project="$(dirname $0)"
export project="$(dirname "$project")"

echo "Removing useless software..."
sudo apt remove -y \
vim-tiny

echo "Upgrading distribution..."
sudo apt dist-upgrade -y
sudo apt update -y
sudo apt upgrade -y
sudo apt autoremove -y

echo "Installing Vim..."
sudo apt install -y xsel vim-gtk
echo "Installing Firefox..."
sudo apt install -y firefox
echo "Installing Zsh..."
sudo apt install -y zsh && chsh -s /bin/zsh
echo "Installing git-lfs"
git lfs install

# Pretty useful software
echo "Installing miscellaneous software..."
sudo apt install -y \
software-properties-common snapd \
exfat-utils exfat-fuse ntfs-3g build-essential \
libssl-dev libreadline-dev inotify-tools
curl -s https://get.sdkman.io | bash # SDKMan for groovy/gradle

# Tmux
echo "Installing tmux and related integrations..."
gsettings set io.elementary.terminal.settings natural-copy-paste false \
&& sudo apt install -y tmux \
&& tic -x "$project/programs/xterm-256color-italic.terminfo" \
&& tic -x "$project/programs/tmux-256color.terminfo"

# Install nvm
echo "Installing Node version manager..."
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash

echo "Installing shell configurations (overwriting Node shell configs)..."
python3 "$project/install/shell.py"

echo "Installing programming languages..."
echo "  - JavaScript"
nvm install v12.13.0
echo "  - Python"
sudo apt install -y python3.7 python2.7 python3-pip python-pip virtualenv
echo "  - Java"
sudo apt install -y default-jre default-jdk
echo "  - Rust"
curl https://sh.rustup.rs -sSf | sh -s -- -y
echo "  - Haskell"
sudo apt install -y haskell-platform
echo "  - Kotlin"
sudo snap install --classic kotlin
echo "  - C"
sudo apt install -y cmake
echo "  - C++"
sudo apt install -y clang clang-format
echo "  - Ruby"
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
rbenv install 2.6.3

echo "Installing tooling..."

echo "  - Ctags"
sudo apt install ctags

echo "  - Ripgrep"
sudo apt-get install ripgrep
