#!/bin/bash

# Assumes Git has already been installed
project="$(dirname $0)"
export project="$(dirname "$project")"

# Updating, upgrading
apt dist-upgrade -y
apt update -y
apt upgrade -y
apt autoremove -y

apt remove vim-tiny -y

# Pretty useful software
apt install -y \
software-properties-common snapd \
exfat-utils exfat-fuse ntfs-3g \
default-jre default-jdk \
build-essential \
conky-all gcalcli \
python3.7 python2.7 \
vim-gtk firefox tmux xsel

# Z Shell
apt install -y zsh
chsh -s /bin/zsh

# Tmux
tic -x "$project/programs/xterm-256color-italic.terminfo"
tic -x "$project/programs/tmux-256color.terminfo"
gsettings set io.elementary.terminal.settings natural-copy-paste false

# Install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
nvm install v12.13.0

source "$project/install/shell"

echo "Running 'rustup' to install the Rust programming langague"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

apt install haskell-platform
