#!/bin/sh
# TODO Make this work better with cloning and stuff; i.e. make it
# so that this works without needing to first install git and clone
project="$(dirname $0)"
export project="$(dirname "$project")"

# Updating, upgrading
apt dist-upgrade -y
apt update -y
apt upgrade -y

# Pretty useful software
apt install -y \
software-properties-common snapd \
exfat-utils exfat-fuse ntfs-3g \
default-jre default-jdk \
build-essential \
conky-all gcalcli \
python3.6 python2.7

