#!/bin/sh

CFG_DIR=`pwd`

read -r -d '' PRINT_TEMPLATE <<- EOF
#!/bin/sh

export CFG_DIR="$CFG_DIR"
CUR_SHELL="\$0"
IS_INTERACTIVE_SHELL=%s

source "$CFG_DIR/shells/dispatch"
EOF

touch "$CFG_DIR/custom/shell_init"
printf "${PRINT_TEMPLATE}\n" 'false' > "$CFG_DIR/custom/shell_init"


touch "$CFG_DIR/custom/shell_interact_init"
printf "${PRINT_TEMPLATE}\n" 'true' > "$CFG_DIR/custom/shell_interact_init"

ln -s "${CFG_DIR}/neovim/init.vim" ~/.vimrc
ln -s "${CFG_DIR}/neovim" ~/.vim
ln -s "${CFG_DIR}/programs/gitconfig" ~/.gitconfig
ln -s "${CFG_DIR}/programs/gitignore_global" ~/.gitignore_global

ln -s "${CFG_DIR}/custom/shell_interact_init" ~/.bashrc
ln -s "${CFG_DIR}/custom/shell_interact_init" ~/.profile
ln -s "${CFG_DIR}/custom/shell_interact_init" ~/.zshrc

