#!/bin/sh

INSTALL_DIR="$(dirname "$(realpath "$0")")"
CFG_DIR="$(dirname "$INSTALL_DIR")"
LOCAL_DIR="${CFG_DIR}/local"
MOVE_DIR="${LOCAL_DIR}/preconf"

# Template for machine-local shell endpoints
PRINT_TEMPLATE="#!/bin/sh\n\
\n\
export CFG_DIR=\"$CFG_DIR\"\nCUR_SHELL=\"\$0\"\n\
IS_INTERACTIVE_SHELL=%s\n\
\n\
source \"$CFG_DIR/shells/dispatch\"\n"

# Sets up machine-local endpoints that can be soft-linked to while still
# maintaining flexibility
touch "$LOCAL_DIR/shell_init"
printf "${PRINT_TEMPLATE}\n" 'false' > "$LOCAL_DIR/shell_init"
touch "$LOCAL_DIR/shell_interact_init"
printf "${PRINT_TEMPLATE}\n" 'true' > "$LOCAL_DIR/shell_interact_init"


# Function to check for existing configs, and move them if necessary
check_move() {
  file_path="$(realpath "~/$1")"
  if test -f "$file_path"; then
    mv "$file_path" "${MOVE_DIR}/$1"
  fi
  ln -s "$(echo "${CFG_DIR}/$2" | tr -s "/")" "$file_path"
}

# Create all the soft links
check_move .vimrc "neovim/init.vim"
check_move .vim "neovim"
check_move .bashrc "/local/shell_interact_init"
check_move .bash_profile "/local/shell_interact_init"
check_move .zshrc "/local/shell_interact_init"

