#!/bin/sh

realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}

move_safe() {
  local src_file_path="$1"
  local dest_file_path="$2"
  local move_file_path="$(dirname "$dest_file_path")/_$(basename "$dest_file_path")"

  if test -f "$dest_file_path"; then
    if [ "$DEBUG" = "true" ]; then
      echo "Detected existing file $dest_file_path, moving it to $move_file_path first"
    fi
    move_safe "$dest_file_path" "$move_file_path"
  elif test -d "$dest_file_path"; then
    if [ "$DEBUG" = "true" ]; then
      echo "Detected existing directory $dest_file_path, moving it to $move_file_path first"
    fi
    move_safe "$dest_file_path" "$move_file_path"
  fi

  mv "$src_file_path" "$dest_file_path"
}

