#!/bin/sh
project="$(dirname $0)"
export project="$(dirname project)"

# Updating, upgrading
apt dist-upgrade
apt update
apt upgrade

# Pretty useful software
apt install \
software-properties-common \
git snapd \
exfat-utils exfat-fuse ntfs-3g \
default-jre default-jdk \
python3.6 python2.7


# NeoVim
# https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu
add-apt-repository ppa:neovim-ppa/stable
apt install neovim
ln -s "${project}/neovim" "~/.config/nvim"
touch ~/.vimrc
echo "runtime ${project}/neovim/init.vim" > ~/.vimrc

# Z Shell
apt install zsh
chsh -s /bin/zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
touch ~/.zshrc
echo "#\!/bin/zsh\n\nsource \"$project/shell/zshrc\"" > ~/.zshrc
touch ~/.zshenv
echo "#\!/bin/zsh\n\nsource \"$project/shell/zshenv\"" > ~/.zshenv

# TODO
# -  Add GNOME stuff and change GNOME software names
# -  Add keyboard shortcut stuff/keybinding stuff

zsh

