#!/bin/bash

# Assumes Git has already been installed
project="$(dirname $0)"
export project="$(dirname "$project")"

sudo echo "Removing useless software..."
sudo apt remove -y vim-tiny
sudo apt autoremove

echo "Upgrading distribution..."
sudo apt dist-upgrade -y
sudo apt update -y
sudo apt upgrade -y
sudo apt autoremove -y

echo "Installing Vim..."
sudo apt install -y xsel vim-gtk
echo "Installing Firefox..."
sudo apt install -y firefox
echo "Installing git-lfs"
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt install git-lfs

# Pretty useful software
echo "Installing miscellaneous software..."
sudo apt install -y \
software-properties-common snapd \
exfat-utils exfat-fuse ntfs-3g build-essential \
libssl-dev libreadline-dev inotify-tools curl

# Install nvm
echo "Installing programming languages..."
echo "  - JavaScript"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
nvm install v12.13.0
echo "  - Java"
sudo apt install -y default-jre default-jdk
echo "  - Rust"
curl https://sh.rustup.rs -sSf | sh -s -- -y
echo "  - C/C++"
sudo apt install -y cmake make clang clang-format
echo "  - Ruby"
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
~/.rbenv/bin/rbenv install 2.6.3 && ~/.rbenv/bin/rbenv global 2.6.3

echo "Installing tooling..."

echo "  - Ctags"
sudo apt install ctags
echo "  - Ripgrep"
sudo apt-get install ripgrep

# Tmux
echo "Installing tmux and related integrations..."
sudo apt-get install -y libevent-dev libncurses-dev \
&& wget https://github.com/tmux/tmux/releases/download/2.7/tmux-2.7.tar.gz \
&& tar -xvzf tmux-2.7.tar.gz \
&& cd tmux-2.7/ \
&& ./configure && make \
&& sudo make install \
&& cd .. \
&& rm -rf ./tmux-2.7* \
&& tic -x "$project/programs/xterm-256color-italic.terminfo" \
&& tic -x "$project/programs/tmux-256color.terminfo"

echo "Fixing keyboard... (will need to restart for changes to take effect)"
sudo cp "$project/compat/linux/x11-keyboard" "/usr/share/X11/xkb/symbols/pc"
