name: Build Static Pages

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: pnpm

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          # version: 0.9.1
          version: 0.10.0-dev.2751+08459ff1c

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Zig
        run: zig build -Drelease-small

          # - name: Clean garbage
          #   run: |
          #     find static/ -name "*.o" -delete
          #     find static/ -name "*.so" -delete
          #     find static/ -name "*.so.0" -delete

      - name: Build Site
        run: pnpm run build

      - name: Add Github files
        run: |
          touch .out/.nojekyll
          echo a1liu.com >> .out/CNAME

      - name: Deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree .out add --all
          git commit -m "Automatic Deploy action run by github-actions"
          git push origin HEAD:gh-pages --force
