name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - production

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.10.0
          cache: yarn

      - name: Next.js Cache
        uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.ts', '**.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build
          yarn export
          touch out/.nojekyll

      - name: Deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree out add --all
          git commit -m "Automatic Deploy action run by github-actions"
          git push origin HEAD:gh-pages --force
